config/routes.rb
Rails.application.routes.draw do
  resources :lancamentos
  resources :tipos
  resources :categorias
  resources :contas
  resources :conta_painel, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lancamento.rb
class Lancamento < ApplicationRecord
  belongs_to :categoria
  belongs_to :tipo
  belongs_to :conta
end

app/controllers/lancamentos_controller.rb
class LancamentosController < ApplicationController
  before_action :set_lancamento, only: [:show, :edit, :update, :destroy]
  before_action :set_titulo

  @@titulo = I18n.t('model.lancamento.titulo')

  # GET /lancamentos
  # GET /lancamentos.json
  def index
    @lancamento = Lancamento.new
    @lancamentos = Lancamento.paginate(page: params[:page], per_page: @@per_page)
  end

  # GET /lancamentos/1
  # GET /lancamentos/1.json
  def show
  end

  # GET /lancamentos/new
  def new
    @lancamento = Lancamento.new
  end

  # GET /lancamentos/1/edit
  def edit
  end

  # POST /lancamentos
  # POST /lancamentos.json
  def create
    @lancamento = Lancamento.new(lancamento_params)

    respond_to do |format|
      if @lancamento.save
        format.html { redirect_to lancamentos_path,  notice: @@titulo + t('msg.salva') }
        format.json { render :show, status: :created, location: @lancamento }
      else
        format.html { redirect_to lancamentos_path, alert: @lancamento.errors.messages }
        format.json { render json: @lancamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lancamentos/1
  # PATCH/PUT /lancamentos/1.json
  def update
    respond_to do |format|
      if @lancamento.update(lancamento_params)
        format.html { redirect_to @lancamento, notice: @@titulo + t('msg.update') }
        format.json { render :show, status: :ok, location: @lancamento }
      else
        format.html { render :edit }
        format.json { render json: @lancamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lancamentos/1
  # DELETE /lancamentos/1.json
  def destroy
    @lancamento.destroy
    respond_to do |format|
      format.html { redirect_to lancamentos_url, notice: @@titulo + t('msg.remove') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lancamento
      @lancamento = Lancamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lancamento_params
      params.require(:lancamento).permit(:nome, :descricao, :valor, :data, :categoria_id, :tipo_id, :conta_id)
    end
end

app/helpers/lancamentos_helper.rb
module LancamentosHelper
end

app/views/lancamentos/_form.html.erb
<%= form_with(model: lancamento, local: true) do |form| %>
  <% if lancamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lancamento.errors.count, "error") %> prohibited this lancamento from being saved:</h2>

      <ul>
      <% lancamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.datetime_select :data %>
  </div>

  <div class="field">
    <%= form.label :categoria_id %>
    <%= form.text_field :categoria_id %>
  </div>

  <div class="field">
    <%= form.label :tipo_id %>
    <%= form.text_field :tipo_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lancamentos/_form_modal.html.erb
<%= form_with(model: lancamento, local: true) do |form| %>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addLancamentoModalLabel">Add Lançamento</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      
        <% if lancamento.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(lancamento.errors.count, "error") %> prohibited this lancamento from being saved:</h2>
    
          <ul>
          <% lancamento.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
        <% end %>
        
        <div class="form-group">
          <label for="lancamento_nome"><%= t('label.nome') %></label>
          <%= form.text_field :nome, {:class => 'form-control',
                                      'placeholder' => "Nome do lançamento",
                                      'aria-describedby' => 'nameHelp'  }%>
        </div>
        <div class="form-group">
          <label for="lancamento_descricao"><%= t('label.descricao') %></label>
          <%= form.text_field :descricao, {:class => 'form-control',
                                      'placeholder' => "Descrição do lançamento"}%>
        </div>
        <div class="form-group">
          <label for="lancamento_valor"><%= t('label.valor') %></label>
          <%= form.text_field :valor, {:class => 'form-control',
                                      'placeholder' => "Valor do lançamento"}%>
        </div>
        <div class="form-group">
          <label for="lancamento_data"><%= t('label.data') %></label>
          <%= form.datetime_select :data, {:class => 'form-control',
                                      'placeholder' => "Data do lançamento"}%>
        </div>
        <div class="form-group">
          <label for="lancamento_categoria_id"><%= t('model.categoria.titulo') %></label>
          <%= form.select :categoria_id, 
                          Categoria.all.collect {|categoria| [categoria.descricao, categoria.id]}, 
                          {:class => 'form-control',
                                     'placeholder' => "Categoria do lançamento"}%>
        </div>
        <div class="form-group">
        <label for="lancamento_tipo_id"><%= t('model.tipo.titulo') %></label>
        <%= form.select :tipo_id, 
                        Tipo.all.collect {|tipo| [tipo.descricao, tipo.id]}, 
                        {:class => 'form-control',
                                   'placeholder' => "Tipo do lançamento"}%>
        </div>
        <div class="form-group">
        <label for="lancamento_conta_id"><%= t('model.conta.titulo') %></label>
        <%= form.select :conta_id, 
                        Conta.all.collect {|conta| [conta.nome, conta.id]}, 
                        {:class => 'form-control',
                                   'placeholder' => "Conta"}%>
        </div>
      </div>
      <div class="modal-footer">
        <%= form.submit t('label.incluir'), :class => "btn btn-primary" %>
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
<% end %>

app/views/lancamentos/edit.html.erb
<h1>Editing Lancamento</h1>

<%= render 'form', lancamento: @lancamento %>

<%= link_to 'Show', @lancamento %> |
<%= link_to 'Back', lancamentos_path %>

app/views/lancamentos/index.html.erb
<div class="container-fluid">
  <div class="container-fluid row">
    <h1><%= @titulo %></h1>
  </div>
  <div class='container-fluid row'>
    <div class="card w-100">
      <div class="card-header">
        <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#addLancamentoModal">
          <i class="material-icons my-0">add</i>
        </button>
      </div>
      <div class="card-body">
        <div class='container-fluid row'>
        <table class="table table-sm table-bordered table-hover">
          <thead class="thead-dark">
            <tr>
              <th scope="col" class="text-center col-md-1"><%= t('label.cod') %></th>
              <th scope="col" class="text-center"><%= t('label.nome') %></th>
              <th scope="col" class="text-center"><%= t('label.descricao') %></th>
              <th scope="col" class="text-center"><%= t('label.valor') %></th>
              <th scope="col" class="text-center"><%= t('label.data') %></th>
              <th scope="col" class="text-center"><%= t('model.categoria.titulo') %></th>
              <th scope="col" class="text-center"><%= t('model.tipo.titulo') %></th>
              <th scope="col" class="text-center col-md-2"><%= t('label.acao') %></th>
            </tr>
          </thead>
          <tbody>
            <% @lancamentos.each do |lancamento| %>
              <tr>
                <th class="align-middle text-center" scope="row"><%= lancamento.id %></th>
                <td class="align-middle"><%= lancamento.nome %></td>
                <td class="align-middle"><%= lancamento.descricao %></td>
                <td class="align-middle"><%= lancamento.valor %></td>
                <td class="align-middle"><%= lancamento.data.strftime("%d/%m/%Y") %></td>
                <td class="align-middle"><%= lancamento.categoria.descricao %></td>
                <td class="align-middle"><%= lancamento.tipo.descricao %></td>
                <td class="my-0 text-center align-middle">
                  <%= link_to lancamento, class: 'btn btn-outline-primary btn-sm' do %><i class="material-icons my-0">search</i><% end %>
                  <%= link_to edit_lancamento_path(lancamento), class: 'btn btn-outline-warning btn-sm' do %><i class="material-icons my-0">create</i><% end %>
                  <%= link_to lancamento, method: :delete, class: 'btn btn-outline-danger btn-sm', data: { confirm: t('msg.confirm') }  do %><i class="material-icons my-0">clear</i><% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="mx-auto">
          <%= will_paginate @lancamentos %>    
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="addLancamentoModal" tabindex="-1" role="dialog" aria-labelledby="addLancamentoModalLabel" aria-hidden="true">
  <%= render 'form_modal', lancamento: @lancamento %>
</div>

app/views/lancamentos/new.html.erb
<h1>New Lancamento</h1>

<%= render 'form', lancamento: @lancamento %>

<%= link_to 'Back', lancamentos_path %>

app/views/lancamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @lancamento.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @lancamento.descricao %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @lancamento.valor %>
</p>

<p>
  <strong>Data:</strong>
  <%= @lancamento.data %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @lancamento.categoria %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @lancamento.tipo %>
</p>

<%= link_to 'Edit', edit_lancamento_path(@lancamento) %> |
<%= link_to 'Back', lancamentos_path %>