config/routes.rb
Rails.application.routes.draw do
  resources :lancamentos
  resources :tipos
  resources :categorias
  resources :contas
  resources :conta_painel, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/conta.rb
class Conta < ApplicationRecord
    validates :nome, presence: true

    has_many :lancamentos
end

app/controllers/contas_controller.rb
class ContasController < ApplicationController
  before_action :set_conta, only: [:show, :edit, :update, :destroy]
  before_action :set_titulo

  @@titulo = I18n.t('model.conta.titulo');

  # GET /conta
  # GET /conta.json
  def index
    @conta = Conta.new
    @contas = Conta.paginate(page: params[:page], per_page: @@per_page)
  end

  # GET /conta/1
  # GET /conta/1.json
  def show
  end

  # GET /conta/new
  def new
    @conta = Conta.new    
  end

  # GET /conta/1/edit
  def edit
    respond_to do |format|
      format.js {render layout: false}
    end
  end

  # POST /conta
  # POST /conta.json
  def create
    @conta = Conta.new(conta_params)

    respond_to do |format|
      if @conta.save
        format.html { redirect_to contas_path, notice: @@titulo + t('msg.salva')}
        format.json { render :index, status: :created, location: @conta }
      else
        format.html { redirect_to contas_path, alert: @conta.errors.messages }
        format.json { render json: @conta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conta/1
  # PATCH/PUT /conta/1.json
  def update
    respond_to do |format|
      if @conta.update(conta_params)
        format.html { redirect_to contas_path, notice: @@titulo + t('msg.update') }
        format.json { render :show, status: :ok, location: @conta }
      else
        format.html { render :edit }
        format.json { render json: @conta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conta/1
  # DELETE /conta/1.json
  def destroy
    @conta.destroy
    params[:id] = nil
    respond_to do |format|
      format.html { redirect_to contas_path, notice: @@titulo + t('msg.remove') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conta
      @conta = Conta.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conta_params
      params.require(:conta).permit(:nome)
    end
end

app/helpers/conta_helper.rb
module ContaHelper

end

app/views/contas/_form.html.erb
<%= form_with(model: conta, local: true) do |form| %>
  <% if conta.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(conta.errors.count, "error") %> prohibited this contum from being saved:</h2>

    <ul>
    <% conta.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <div class="form-row align-items-center">
    <div class="col-auto">
      <label class="col-form-label mb-2" for="nomeField"><%= t('model.conta.titulo') %></label>
    </div>
    <div class="col-auto">
      <%= form.text_field :nome, :class => "form-control mb-2", 'autofocus'=>"autofocus", :id => "nomeField", :placeholder => t('label.nome') %>
    </div>
    <div class="col-auto">
      <%= form.submit t('label.incluir'), :class => "btn btn-primary mb-2" %>
    </div>
  </div>
<% end %>

app/views/contas/_form_modal.html.erb
<%= form_with(model: conta, local: true) do |form| %>
<div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addLancamentoModalLabel">Edit Conta</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      
        <% if conta.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(conta.errors.count, "error") %> prohibited this lancamento from being saved:</h2>
    
          <ul>
          <% conta.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
        <% end %>
        
        <div class="form-group">
          <label for="conta_nome"><%= t('label.nome') %></label>
          <%= form.text_field :nome, {:class => 'form-control',
                                      'placeholder' => "Nome da Conta",
                                      'aria-describedby' => 'nameHelp'  }%>
        </div>
      </div>
      <div class="modal-footer">
        <%= form.submit t('label.salvar'), :class => "btn btn-primary", data: {"disable-with": "Salvando"} %>
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>>
  <% end %>

app/views/contas/_show.html.erb
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Tete</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
<div class="modal-body">
        ...
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>

app/views/contas/edit.html.erb
$("#formModal").html("<%= escape_javascript(render partial: 'form_modal', 
                                                     locals: { conta: @conta } ) %>");
$("#formModal").modal("show");

app/views/contas/index.html.erb
<div class="container-fluid">
  <div class="container-fluid row">
    <h1><%= @titulo %></h1>
  </div>
  <div class='container-fluid row'>
    <div class="card w-100">
      <div class="card-header">
        <%= render 'form', conta: @conta %>
      </div>
      <div class="card-body">
        <%= datatable(@contas, ['nome'])%>
      </div>
    </div>
  </div>
</div>

app/views/contas/new.html.erb
<h1>New Conta</h1>

<%= render 'form', conta: @conta %>

<%= link_to 'Back', contas_path %>

app/views/contas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @conta.nome %>
</p>

<%= link_to 'Edit', edit_conta_path(@conta), class: ['btn btn-primary']  %> |
<%= link_to 'Back', contas_path, class: ['btn btn-danger'] %>