config/routes.rb
Rails.application.routes.draw do
  resources :lancamentos
  resources :tipos
  resources :categorias
  resources :contas
  resources :conta_painel, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tipo.rb
class Tipo < ApplicationRecord

  validates :descricao, presence: true
  
  has_many :lancamentos
end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController
  before_action :set_tipo, only: [:show, :edit, :update, :destroy]
  before_action :set_titulo

  @@titulo = I18n.t('model.tipo.titulo');

  # GET /tipos
  # GET /tipos.json
  def index
    @tipo = Tipo.new
    @tipos = Tipo.paginate(page: params[:page], per_page: @@per_page)
  end

  # GET /tipos/1
  # GET /tipos/1.json
  def show
  end

  # GET /tipos/new
  def new
    @tipo = Tipo.new
  end

  # GET /tipos/1/edit
  def edit
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  # POST /tipos
  # POST /tipos.json
  def create
    @tipo = Tipo.new(tipo_params)

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to tipos_path,  notice: @@titulo + t('msg.salva') }
        format.json { render :show, status: :created, location: @tipo }
      else
        format.html { redirect_to tipos_path, alert: @tipo.errors.messages }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipos/1
  # PATCH/PUT /tipos/1.json
  def update
    respond_to do |format|
      if @tipo.update(tipo_params)
        format.html { redirect_to tipos_path, notice: @@titulo + t('msg.update') }
        format.json { render :show, status: :ok, location: @tipo }
      else
        format.html { render :edit }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipos/1
  # DELETE /tipos/1.json
  def destroy
    @tipo.destroy
    respond_to do |format|
      format.html { redirect_to tipos_url, notice: @@titulo + t('msg.remove') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo
      @tipo = Tipo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_params
      params.require(:tipo).permit(:descricao)
    end
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/tipos/_form.html.erb
<%= form_with(model: tipo, local: true) do |form| %>
  <% if tipo.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(tipo.errors.count, "error") %> prohibited this contum from being saved:</h2>

    <ul>
    <% v.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <div class="form-row align-items-center">
    <div class="col-auto">
      <label class="col-form-label mb-2" for="descricaoField"><%= t('model.tipo.titulo') %></label>
    </div>
    <div class="col-auto">
      <%= form.text_field :descricao, :class => "form-control mb-2", 'autofocus'=>"autofocus", :id => "descricaoField", :placeholder => t('label.descricao') %>
    </div>
    <div class="col-auto">
      <%= form.submit t('label.incluir'), :class => "btn btn-primary mb-2" %>
    </div>
  </div>
<% end %>

app/views/tipos/_form_modal.html.erb
<%= form_with(model: tipo, local: true) do |form| %>
<div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addLancamentoModalLabel">Edit Tipo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      
        <% if tipo.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(tipo.errors.count, "error") %> prohibited this lancamento from being saved:</h2>
    
          <ul>
          <% tipo.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
        <% end %>
        
        <div class="form-group">
          <label for="tipo_descricao"><%= t('label.descricao') %></label>
          <%= form.text_field :descricao, {:class => 'form-control',
                                      'placeholder' => "Descrição do Tipo",
                                      'aria-describedby' => 'descricaoHelp'  }%>
        </div>
      </div>
      <div class="modal-footer">
        <%= form.submit t('label.salvar'), :class => "btn btn-primary", data: {"disable-with": "Salvando"} %>
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>>
  <% end %>

app/views/tipos/edit.html.erb
$("#formModal").html("<%= escape_javascript(render partial: 'form_modal', 
                                                     locals: { tipo: @tipo } ) %>");
$("#formModal").modal("show");

app/views/tipos/index.html.erb
<div class="container-fluid">
  <div class="container-fluid row">
    <h1><%= @titulo %></h1>
  </div>
  <div class='container-fluid row'>
    <div class="card w-100">
      <div class="card-header">
        <%= render 'form', tipo: @tipo %>
      </div>
      <div class="card-body">
        <%= datatable(@tipos, ['descricao'])%>
      </div>
    </div>
  </div>
</div>

app/views/tipos/new.html.erb
<h1>New Tipo</h1>

<%= render 'form', tipo: @tipo %>

<%= link_to 'Back', tipos_path %>

app/views/tipos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @tipo.descricao %>
</p>

<%= link_to 'Edit', edit_tipo_path(@tipo) %> |
<%= link_to 'Back', tipos_path %>