config/routes.rb
Rails.application.routes.draw do
  resources :lancamentos
  resources :tipos
  resources :categorias
  resources :contas
  resources :conta_painel, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alert.html.erb
<% if notice %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong>Info:</strong> <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>
<% if alert %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <strong>Alerta!</strong> <%= alert %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="row">
  <div class="col-sm">
  <nav class="navbar navbar-dark bg-dark fixed-bottom">
    <a class="navbar-brand" href="#">Footer</a>
  </nav>
  </div>
</div>

app/views/layouts/_head.html.erb
<div class="row">
  <div class="col-sm">
  <nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-lg">
    <a class="navbar-brand" href="#">MYWALLET</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= render 'layouts/menu' %>
  </nav>
  </div>
</div>

app/views/layouts/_menu.html.erb
<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" 
          data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Geral
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="<%= conta_painel_index_path %>">Conta Painel</a>
        <a class="dropdown-item" href="<%= contas_path %>">Contas</a>
        <a class="dropdown-item" href="<%= categorias_path %>">Categorias</a>
        <a class="dropdown-item" href="<%= tipos_path %>">Tipos</a>
        <a class="dropdown-item" href="<%= lancamentos_path %>">Lançamentos</a>
      </div>
    </li>
  </ul>
  <form class="form-inline my-2 my-lg-0">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-default my-2 my-sm-0" type="submit">Search</button>
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MYWALLET</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render 'layouts/head' %>

      <div class="row py-4 my-4">
          <div class="col-sm">
          <%= render 'layouts/alert' %> 
          <%= yield %>
        </div>
      </div>
      
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>